version: '3'
services:
    app:
        build:
            dockerfile: dockerfile
        container_name: ML_Flask_App
        restart: unless-stopped
        ports:
            - "5000:5000"
        command:
            serve -s build -p 5000
   